### ISSUE TITLE
App Crashed when permission granted!

### ISSUE THREAD

**Issue by saeedhpro** [kevincaicedo/imei_plugin#19]
Application crashed when permission granted for first time.

java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=1995, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.example.send_tracking_app/com.example.send_tracking_app.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/AndroidRuntime( 7481): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4089)
E/AndroidRuntime( 7481): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4132)
E/AndroidRuntime( 7481): 	at android.app.ActivityThread.-wrap20(ActivityThread.java)
E/AndroidRuntime( 7481): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1533)
E/AndroidRuntime( 7481): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 7481): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime( 7481): 	at android.app.ActivityThread.main(ActivityThread.java:6119)
E/AndroidRuntime( 7481): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7481): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
E/AndroidRuntime( 7481): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
E/AndroidRuntime( 7481): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/AndroidRuntime( 7481): 	at com.rioapp.demo.imeiplugin.ImeiPlugin.getImei(ImeiPlugin.java:77)
E/AndroidRuntime( 7481): 	at com.rioapp.demo.imeiplugin.ImeiPlugin.onRequestPermissionsResult(ImeiPlugin.java:123)
E/AndroidRuntime( 7481): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEnginePluginRegistry.java:612)
E/AndroidRuntime( 7481): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onRequestPermissionsResult(FlutterEnginePluginRegistry.java:356)
E/AndroidRuntime( 7481): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:509)
E/AndroidRuntime( 7481): 	at io.flutter.embedding.android.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:611)
E/AndroidRuntime( 7481): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7084)
E/AndroidRuntime( 7481): 	at android.app.Activity.dispatchActivityResult(Activity.java:6936)
E/AndroidRuntime( 7481): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4085)
E/AndroidRuntime( 7481): 	... 9 more
I/Process ( 7481): Sending signal. PID: 7481 SIG: 9

**Comment by arbeeorlar** [comment]
I am facing the same problem

**Comment by 50431040** [comment]
+1
